# Generated by Django 4.0.5 on 2023-10-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='current_price',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
